name: Test Ruby Gem
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  ruby:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Check ruby
        working-directory: ./ruby
        run: |
          bundle install
          bundle exec rake spec
